vertigobr/vkpr-cli

vkpr/init/src/unix/formula/formula.sh
- [X ] Bug fix (non-breaking issue)
=> fix(init) changing install scripts to not ask for root password

lib/functions/log.sh
=> fix(log.sh) bold logs update

lib/functions/validate.sh, vkpr/aws/eks/init/src/unix/formula/formula.sh
- [X ] New feature (non-breaking change which adds functionality)
=> feat(aws/eks): entering and running EKS cluster information validators

lib/validator/devportal.sh, lib/validator/okta.sh, lib/validator/validators.sh, vkpr/devportal/install/src/unix/formula/formula.sh
feat(devportal): adding okta and devportal validators
feat(validator)adding namespace validator
=> Vkpr 614 677

lib/validator/argocd.sh, vkpr/argocd/install/config.json, vkpr/argocd/install/src/unix/formula/formula.sh
=> Vkpr 614 591

lib/validator/okta.sh
fix (devportal): fix okta secret validator
VKPR-720
- [ X] Bug fix (non-breaking issue)
=> fix (devportal): fix okta secret validator

vkpr/devportal/install/config.json
feat(devportal) changing the spechouseurl parameter assignment method
VKPR-735
- [] Bug fix (non-breaking issue)
=> feat(devportal) changing the spechouseurl parameter assignment method

lib/validator/vault.sh, vkpr/vault/install/config.json, vkpr/vault/install/src/unix/formula/formula.sh
feat(vault) create validators and update formula
VKPR-694-N
=> feat(vault) create validators and update formula

lib/validator/loki.sh
=> feat(loki) updating error message

lib/validator/kong.sh
=> feat(kong) updating error message

lib/validator/jaeger.sh
=> feat(jaeger) updating error message

lib/validator/gitlab.sh
=> feat(gitlab) updating error message

lib/validator/infra.sh
=> feat(infra) updating error message

lib/validator/ingress.sh
=> feat(ingress) updating error message

lib/validator/devportal.sh
=> feat(devportal) updating error message

lib/validator/certmanager.sh
=> feat(certmanager) updating error message

lib/validator/consul.sh
=> feat(consul) updating error message

lib/validator/digitalocean.sh, vkpr/digitalocean/cluster/init/src/unix/formula/formula.sh
Create validate inputs and updating error message
VKPR-742-N
Yes
=> feat(digitalocean) create validate inputs and updating error message

lib/validator/argocd.sh
=> feat(argocd) updating error message

lib/validator/okta.sh
=> feat(okta) updating error message

lib/validator/postgresql.sh
=> feat(postgresql) updating error message

vkpr/mockserver/install/config.json
fix(mockeserver) changing true false from config.json
VKPR-753
=> fix(mockserver) changing true false from config.json

lib/validator/external-dns.sh
=> feat(external-dns) updating error message

vkpr/okteto/init/src/unix/formula/formula.sh
adding namespace okteto selector
VKPR-815
=> feat(okteto) adding namespace okteto selector

vkpr/kong/install/src/unix/formula/formula.sh
Fix crd kong dbless in okteto
VKPR-829
=> fix(kong) fix crd kong dbless in okteto

vkpr/aws/eks/init/config.json, vkpr/aws/eks/init/src/unix/formula/formula.sh
=> aws(feat) update version inputs

vkpr/github/parameter/add/src/unix/formula/formula.sh
=> fix(github) fix validators parameter add

vkpr/aws/eks/init/src/unix/formula/github.sh, vkpr/aws/eks/init/src/unix/formula/gitlab.sh
=> Ajustes de strings EKS

vkpr/aws/eks/init/src/unix/formula/formula.sh, vkpr/aws/eks/init/src/unix/formula/gitlab.sh
=> Vkpr GitHub

vkpr/aws/eks/init/src/unix/formula/github.sh
=> Ajuste Workspace e infracose um contexto novo?

vkpr/aws/eks/init/src/unix/formula/github.sh
=> Ajuste Backend

lib/validator/validators.sh
fix(validators) fixing volume validator to work on macOs
=> fix(validators) fixing volume validator to work on macOs

vkpr/init/src/unix/formula/formula.sh
=> fix(init) adding check sudo for docker usage

vkpr/kong/install/src/unix/formula/setting/kong-standard-ba.sh, vkpr/kong/install/src/unix/formula/setting/kong-standard.sh
=> fix(kong) fix manager and api ingress hosts
